#!/usr/bin/env bash
#Displays numbers from 1 to 100
y=1
while [ $y -ne 101 ]
do
    if [ $((y % 15)) -eq 0 ]
    then
	echo "FizzBuzz"
    elif [ $((y % 3)) -eq 0 ]
    then
	echo "Fizz"
    elif [ $((y % 5)) -eq 0 ]
    then
        echo "Buzz"
    else
	echo $y
    fi
    ((y++))
done

