#!/usr/bin/env bash
#Displays Best School 10 times
y=1
while [ "$y" -le 10 ]
do
      if [ "$y" -eq 9 ]
      then
          echo "Best School"
          echo "Hi"
      else
          echo "Best School"
      fi
      y=$((y+1))
done
