#!/usr/bin/env bash
#Displays numbers from 1 to 20 
y=1
while [ "$y" -le 20 ]
do
	if [ "$y" -eq 4 ]
	then
	   echo "bad luck from China"
	elif [ "$y" -eq 9 ]
	then
	   echo "bad luck from Japan"
	elif [ "$y" -eq 17 ]
	then
	   echo "bad luck from Italy"
	else	
                echo "Best School"
	fi	
	y=$((y+1))
done

