#!/usr/bin/env bash
# This script is displaying "Best School" 10 times but prints Hi at 9
y=1
while ((y < 21))
do
	echo $y
	case "$y" in
		4) echo "bad luck from China";;
		9) echo "bad luck from Japan";;
		17) echo "bad luck from Italy";;
		esac
	((y++))
done

