#!/usr/bin/env bash
#Displays time for 12 hours 59 minutes
hours=0
minutes=1
while [ $hours -ne 12 ]
do
    echo "Hour: $hours"
    ((hours++))
    while [ $minutes -ne 59 ]
    do
	echo $minutes
	((minutes++))
    done
    ((minutes = 1))
done


